layout_spectrum: 0.4170209
typography_spectrum: 0.04585101
color:
  saturation: 0.00708843
  lightness: 0.8423014
  brandStrength: 0.1352347
  rhythmicContrast: 0.5255239
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: EldridgeWeddingJAM
